= DBCPConnectionPoolLookup 2.2.0

Provides a DBCPService that can be used to dynamically select another DBCPService. This service requires an attribute named 'database.name' to be passed in when asking for a connection, and will throw an exception if the attribute is missing. The value of 'database.name' will be used to select the DBCPService that has been registered with that name. This will allow multiple DBCPServices to be defined and registered, and then selected dynamically at runtime by tagging flow files with the appropriate 'database.name' attribute.

[horizontal]
*Tags* (Ключевые слова):
connection, database, dbcp, jdbc, pooling, store
[horizontal]
*Input Requirement* (Требования к вводу данных):

[horizontal]
*Supports Sensitive Dynamic* (Поддержка динамически изменяемых параметров, которые могут содержать конфиденциальную информацию):
 False (Нет) 



== Properties (Свойства)




== Динамические свойства

[width="100%",cols="1a,2a,1a,1a",options="header",]
|===
|Наименование |Описание |Значение |Ограничения языка выражений

|`The name to register DBCPService`
|If 'database.name' attribute contains the name of the dynamic property, then the DBCPService (registered in the value) will be selected.
|`The DBCPService`
|

|===



















