= RecordSinkServiceLookup 2.2.0

Provides a RecordSinkService that can be used to dynamically select another RecordSinkService. This service requires an attribute named 'record.sink.name' to be passed in when asking for a connection, and will throw an exception if the attribute is missing. The value of 'record.sink.name' will be used to select the RecordSinkService that has been registered with that name. This will allow multiple RecordSinkServices to be defined and registered, and then selected dynamically at runtime by tagging flow files with the appropriate 'record.sink.name' attribute. Note that this controller service is not intended for use in reporting tasks that employ RecordSinkService instances, such as QueryNiFiReportingTask.

[horizontal]
*Tags* (Ключевые слова):
lookup, record, sink
[horizontal]
*Input Requirement* (Требования к вводу данных):
 (Обязательно)
[horizontal]
*Supports Sensitive Dynamic* (Поддержка динамически изменяемых параметров, которые могут содержать конфиденциальную информацию):
 False (Нет) 



== Properties (Свойства)




== Динамические свойства

[width="100%",cols="1a,2a,1a,1a",options="header",]
|===
|Наименование |Описание |Значение |Ограничения языка выражений

|`The name to register the specified RecordSinkService`
|If 'record.sink.name' attribute contains the name of the dynamic property, then the RecordSinkService (registered in the value) will be selected.
|`The RecordSinkService`
|

|===



















