= RenameRecordField 2.2.0

Переименовывает одно или несколько полей в каждом Record FlowFile. Этот процессор требует, чтобы было добавлено хотя бы одно пользовательское свойство. Имя свойства должно указывать на путь записи, который определяет поле для обновления. Значение свойства — это новое имя, которое будет присвоено полю записи, соответствующему пути записи. Свойство значения может использовать выражения языка для ссылки на атрибуты FlowFile, а также переменные `field.name`, `field.value`, `field.type` и `record.index`.

[horizontal]
*Tags* (Ключевые слова):
avro, csv, field, generic, json, log, logs, record, rename, schema, update
[horizontal]
*Input Requirement* (Требования к вводу данных):
REQUIRED
[horizontal]
*Supports Sensitive Dynamic* (Поддержка динамически изменяемых параметров, которые могут содержать конфиденциальную информацию):
 False (Нет) 



== Properties (Свойства)


.*Record Reader*
************************************************
[horizontal]
*DISPLAY NAME (Отображаемое наименование):*:: Record Reader (Записыватель записей)

[horizontal]
*DESCRIPTION (Описание):*:: Указывает контроллер сервиса для использования при чтении входящих данных


[horizontal]
*EXPRESSION LANGUAGE SCOPE (Область видимости языка выражений):*:: Not Supported (Не поддерживается)
[horizontal]
*SENSITIVE (Содержит конфиденциальные данные):*::  False (Нет) 

[horizontal]
*REQUIRED (Обязательный параметр):*::  True (Да) 
************************************************
.*Record Writer*
************************************************
[horizontal]
*DISPLAY NAME (Отображаемое наименование):*:: Record Writer (Записыватель записей)

[horizontal]
*DESCRIPTION (Описание):*:: Указывает контроллер сервиса для использования при записи записей


[horizontal]
*EXPRESSION LANGUAGE SCOPE (Область видимости языка выражений):*:: Not Supported (Не поддерживается)
[horizontal]
*SENSITIVE (Содержит конфиденциальные данные):*::  False (Нет) 

[horizontal]
*REQUIRED (Обязательный параметр):*::  True (Да) 
************************************************


== Динамические свойства

[width="100%",cols="1a,2a,1a,1a",options="header",]
|===
|Наименование |Описание |Значение |Ограничения языка выражений

|`A RecordPath that identifies which field(s) to update`
|Позволяет пользователям указать новое имя для каждого поля, соответствующего пути записи.
|`The new name to assign to the Record field`
|

|===









=== Relationships (Связи)

[cols="1a,2a",options="header",]
|===
|Наименование |Описание

|`success`
|FlowFiles, которые успешно преобразованы, будут направлены в это отношение

|`failure`
|Если FlowFile не может быть преобразован из конфигурированного входного формата в требуемый выходной формат, неизмененный FlowFile будет направлен в это отношение

|===





=== Writes Attributes (Записываемые атрибуты)

[cols="1a,2a",options="header",]
|===
|Наименование |Описание

|`record.index`
|Это атрибут предоставляет текущий индекс строки и доступен только внутри выражения литерального значения.

|===



== Варианты использования
:sectnums:



=== Переименовать поле в каждом Record в конкретное, известное имя.


NOTE: 



Ключевые слова::
rename
field
static
specific
name



.Конфигурация
====
Configure the 'Record Reader' according to the input format.
Configure the 'Record Writer' according to the desired output format.

Add a property to the Processor such that the name of the property is a RecordPath to identifies the field to rename. The value of the property is the new name to assign to the Record Field that matches the RecordPath.

For example, to rename the `name` field to `full_name`, add a property with a name of `/name` and a value of `full_name`.

Many properties can be added following this pattern in order to rename multiple fields.
====


=== Переименовать поле в каждом Record в имя, которое является производным от атрибута FlowFile.


NOTE: 



Ключевые слова::
rename
field
expression language
EL
flowfile
attribute



.Конфигурация
====
Configure the 'Record Reader' according to the input format.
Configure the 'Record Writer' according to the desired output format.

Add a property to the Processor such that the name of the property is a RecordPath to identifies the field to rename. The value of the property is an Expression Language expression that can be used to determine the new name of the field.

For example, to rename the `addr` field to whatever value is stored in the `preferred_address_name` attribute, add a property with a name of `/name` and a value of `${preferred_address_name}`.

Many properties can be added following this pattern in order to rename multiple fields.
====


=== Переименовать поле в каждом Record в новое имя, которое является производным от текущего имени поля.


NOTE: Это может быть использовано, например, для добавления префикса или суффикса к некоторым полям или для трансформации имени поля в верхний регистр.



Ключевые слова::
rename
field
expression language
EL
field.name



.Конфигурация
====
Configure the 'Record Reader' according to the input format.
Configure the 'Record Writer' according to the desired output format.

Add a property to the Processor such that the name of the property is a RecordPath to identifies the field to rename. The value of the property is an Expression Language expression that references the `field.name` property.

For example, to rename all fields with a prefix of `pre_`, we add a property named `/*` and a value of `pre_${field.name}`. If we would like this to happen recursively, to nested fields as well, we use a property name of `//*` with the value of `pre_${field.name}`.

To make all field names uppercase, we can add a property named `//*` with a value of `${field.name:toUpper()}`. Many properties can be added following this pattern in order to rename multiple fields.
====






=== Смотрите также


* xref:Processors/RemoveRecordField.adoc[RemoveRecordField]

* xref:Processors/UpdateRecord.adoc[UpdateRecord]


