= RouteOnAttribute 2.2.0

Маршрутизирует FlowFiles на основе их атрибутов, используя язык выражений атрибутов

[horizontal]
*Tags* (Ключевые слова):
Язык выражений атрибутов, Выражение языка, Регулярное выражение, атрибуты, обнаружить, фильтровать, найти, регэксп, маршрутизация, поиск, строка, текст
[horizontal]
*Input Requirement* (Требования к вводу данных):
REQUIRED
[horizontal]
*Supports Sensitive Dynamic* (Поддержка динамически изменяемых параметров, которые могут содержать конфиденциальную информацию):
 False (Нет) 



== Properties (Свойства)


.*Routing Strategy*
************************************************
[horizontal]
*DISPLAY NAME (Отображаемое наименование):*:: Routing Strategy (Стратегия маршрутизации)

[horizontal]
*DESCRIPTION (Описание):*:: Указывает, как определить, какое отношение использовать при оценке выражения на языке Expression Language


[horizontal]
*EXPRESSION LANGUAGE SCOPE (Область видимости языка выражений):*:: Not Supported (Не поддерживается)
[horizontal]
*SENSITIVE (Содержит конфиденциальные данные):*::  False (Нет) 

[horizontal]
*ALLOWABLE VALUES (Допустимые значения):*::

* Route to Property name (Маршрутизация к имени свойства): Копия FlowFile будет направлена в каждое отношение, соответствующее выражению которого оценивается как 'true' 

* Route to 'matched' if all match (Маршрутизация к 'соответствует', если все совпадают): Требует, чтобы все пользовательские выражения оценивались как 'true' для того, чтобы FlowFile считался соответствующим 

* Route to 'matched' if any matches (Маршрутизация к 'соответствует', если хотя бы одно совпадает): Требует, чтобы по крайней мере одно из пользовательских выражений оценивалось как 'true' для того, чтобы FlowFile считался соответствующим 


[horizontal]
*REQUIRED (Обязательный параметр):*::  True (Да) 
************************************************


== Динамические свойства

[width="100%",cols="1a,2a,1a,1a",options="header",]
|===
|Наименование |Описание |Значение |Ограничения языка выражений

|`Relationship Name`
|Направляет FlowFiles, атрибуты которых соответствуют выражению языка в значении динамического свойства, к Relationship, указанному в ключе динамического свойства
|`Выражение языка, возвращающее логическое значение, указывающее, должен ли FlowFile быть направлен к этому Relationship`
|

|===









=== Relationships (Связи)

[cols="1a,2a",options="header",]
|===
|Наименование |Описание

|`unmatched`
|FlowFiles, которые не соответствуют ни одному пользовательскому выражению, будут направлены сюда

|===





=== Writes Attributes (Записываемые атрибуты)

[cols="1a,2a",options="header",]
|===
|Наименование |Описание

|`RouteOnAttribute.Route`
|Отношение, к которому был направлен FlowFile

|===



== Варианты использования
:sectnums:



=== Маршрутизировать данные в одно или несколько отношений на основе их атрибутов, используя язык выражений NiFi.


NOTE: 



Ключевые слова::
атрибуты
маршрутизация
выражение языка



.Конфигурация
====
Установите свойство "Routing Strategy" в значение "Route to Property name".
Для каждого маршрута, к которому может быть направлен FlowFile, добавьте новое свойство. Имя свойства должно описывать маршрут.
Значение свойства — это выражение языка атрибутов, возвращающее логическое значение, указывающее, должен ли данный FlowFile быть направлен к соответствующему отношению.

Например, мы можем маршрутизировать данные на основе их расширения файла, используя следующие свойства:
    - "Routing Strategy" = "Route to Property Name"
    - "jpg" = "${filename:endsWith('.jpg')}"
    - "png" = "${filename:endsWith('.png')}"
    - "pdf" = "${filename:endsWith('.pdf')}"

Теперь у процессора будет 3 отношения: `jpg`, `png` и `pdf`. Каждое из этих отношений должно быть подключено к соответствующему downstream-процессору.
====


=== Оставить данные только в случае, если их атрибуты удовлетворяют некоторым критериям, например, если их имя файла заканчивается на .txt.


NOTE: 



Ключевые слова::
оставить
фильтровать
удалить
выражение языка



.Конфигурация
====
Добавьте новое свойство для каждого условия, которое должно быть выполнено для сохранения данных.
Если данные должны быть сохранены в случае выполнения любого из предоставленных условий, установите свойство "Routing Strategy" в значение "Route to 'matched' if any matches".
Если для сохранения данных должны быть выполнены все условия, установите свойство "Routing Strategy" в значение "Route to 'matched' if all match".

Например, чтобы оставить файлы, имя файла которых заканчивается на .txt и имеет размер не менее 1000 байт, мы будем использовать следующие свойства:
    - "ends_with_txt" = "${filename:endsWith('.txt')}"
    - "large_enough" = "${fileSize:ge(1000)}
    - "Routing Strategy" = "Route to 'matched' if all match"
====


=== Отбросить или удалить файл на основе атрибутов, таких как имя файла.


NOTE: 



Ключевые слова::
отбросить
удалить
фильтровать
удалить
выражение языка



.Конфигурация
====
Добавьте новое свойство для каждого условия, которое должно быть выполнено для удаления данных.
Если данные должны быть удалены в случае выполнения любого из предоставленных условий, установите свойство "Routing Strategy" в значение "Route to 'matched' if any matches".
Если для удаления данных должны быть выполнены все условия, установите свойство "Routing Strategy" в значение "Route to 'matched' if all match".

Примеры конфигурации свойств:
    Пример 1 Случай использования: Данные должны быть удалены, если их атрибут "uuid" содержит 'a' или заканчивается на '0'.
      Здесь мы будем использовать следующие свойства:
        - "has_a" = "${uuid:contains('a')}"
        - "ends_with_0" = "${uuid:endsWith('0')}
        - "Routing Strategy" = "Route to 'matched' if any matches"
    Пример 2 Случай использования: Данные должны быть удалены, если их атрибут 'uuid' содержит 'a' И заканчивается на '1'.
      Здесь мы будем использовать следующие свойства:
        - "has_a" = "${uuid:contains('a')}"
        - "ends_with_1" = "${uuid:endsWith('1')}
        - "Routing Strategy" = "Route to 'matched' if all match"
====




== Варианты использования, включающие другие компоненты


=== Маршрутизировать данные, ориентированные на записи, на основе того, удовлетворяют ли значения записи определенным критериям


NOTE: 



Ключевые слова::

запись

маршрутизация

содержимое

данные








