= UpdateRecord 2.2.0

Обновляет содержимое FlowFile, содержащего данные в формате записи (т.е. данные, которые можно читать с помощью RecordReader и записывать с помощью RecordWriter). Этот процессор требует наличия по крайней мере одного пользовательского свойства. Имя свойства должно указывать на путь записи, который определяет поле для обновления. Значение свойства либо является замещающим значением (при необходимости используя Expression Language), либо самим путем записи, извлекающим значение из записи. Будет ли значение свойства определено как путь записи или литеральное значение, зависит от конфигурации свойства <Стратегия значения замены>.

[horizontal]
*Tags* (Ключевые слова):
avro, csv, freeform, generic, json, log, logs, record, schema, text, update
[horizontal]
*Input Requirement* (Требования к вводу данных):
REQUIRED
[horizontal]
*Supports Sensitive Dynamic* (Поддержка динамически изменяемых параметров, которые могут содержать конфиденциальную информацию):
 False (Нет) 



== Properties (Свойства)


.*Record Reader*
************************************************
[horizontal]
*DISPLAY NAME (Отображаемое наименование):*:: Record Reader (Записыватель записей)

[horizontal]
*DESCRIPTION (Описание):*:: Указывает контроллер сервиса для использования при чтении входящих данных


[horizontal]
*EXPRESSION LANGUAGE SCOPE (Область видимости языка выражений):*:: Not Supported (Не поддерживается)
[horizontal]
*SENSITIVE (Содержит конфиденциальные данные):*::  False (Нет) 

[horizontal]
*REQUIRED (Обязательный параметр):*::  True (Да) 
************************************************
.*Record Writer*
************************************************
[horizontal]
*DISPLAY NAME (Отображаемое наименование):*:: Record Writer (Записыватель записей)

[horizontal]
*DESCRIPTION (Описание):*:: Указывает контроллер сервиса для использования при записи записей


[horizontal]
*EXPRESSION LANGUAGE SCOPE (Область видимости языка выражений):*:: Not Supported (Не поддерживается)
[horizontal]
*SENSITIVE (Содержит конфиденциальные данные):*::  False (Нет) 

[horizontal]
*REQUIRED (Обязательный параметр):*::  True (Да) 
************************************************
.*Replacement Value Strategy*
************************************************
[horizontal]
*DISPLAY NAME (Отображаемое наименование):*:: Replacement Value Strategy (Стратегия замены значений)

[horizontal]
*DESCRIPTION (Описание):*:: Указывает, как интерпретировать настроенные значения замены


[horizontal]
*EXPRESSION LANGUAGE SCOPE (Область видимости языка выражений):*:: Not Supported (Не поддерживается)
[horizontal]
*SENSITIVE (Содержит конфиденциальные данные):*::  False (Нет) 

[horizontal]
*ALLOWABLE VALUES (Допустимые значения):*::

* Literal Value (Литеральное значение): Значение, введенное для свойства (после оценки выражения языка) является желаемым значением для обновления полей записи. Выражение языка может ссылаться на переменные 'field.name', 'field.type' и 'field.value', чтобы получить информацию о поле и значении оцениваемого поля. 

* Record Path Value (Значение пути записи): Значение, введенное для свойства (после оценки выражения языка) не является литеральным значением, а скорее путём записи, который должен быть оценен относительно записи, и результат пути записи будет использован для обновления записи. Обратите внимание, что если выбран этот параметр, и путь записи приводит к нескольким значениям для данной записи, входной поток File будет направлен в отношение 'failure'. 


[horizontal]
*REQUIRED (Обязательный параметр):*::  True (Да) 
************************************************


== Динамические свойства

[width="100%",cols="1a,2a,1a,1a",options="header",]
|===
|Наименование |Описание |Значение |Ограничения языка выражений

|`A RecordPath.`
|Позволяет пользователям указывать значения для замены полей в записи, соответствующих RecordPath.
|`The value to use to replace fields in the record that match the RecordPath`
|

|===









=== Relationships (Связи)

[cols="1a,2a",options="header",]
|===
|Наименование |Описание

|`success`
|FlowFiles, которые успешно преобразованы, будут направлены в это отношение

|`failure`
|Если FlowFile не может быть преобразован из конфигурируемого входного формата в конфигурируемый выходной формат, неизмененный FlowFile будет направлен в это отношение

|===





=== Writes Attributes (Записываемые атрибуты)

[cols="1a,2a",options="header",]
|===
|Наименование |Описание

|`record.index`
|Это атрибут предоставляет текущий индекс строки и доступен только внутри выражения литерального значения.

|`record.error.message`
|При сбое предоставляет сообщение об ошибке, которое встретилось Reader или Writer.

|===



== Варианты использования
:sectnums:



=== Объединить несколько полей в одно поле.


NOTE: 



Ключевые слова::
combine
concatenate
recordpath



.Конфигурация
====
"Replacement Value Strategy" = "Record Path Value"

A single additional property is added to the Processor. The name of the property should indicate a RecordPath that determines the field that should be updated.
The value of the property uses the CONCAT Record Path function to concatenate multiple values together, potentially using other string literal values.
For example, to combine the `title`, `firstName` and `lastName` fields into a single field named `fullName`, we add a property with the name `/fullName` and a value of `CONCAT(/title, ' ', /firstName, ' ', /lastName)`
====


=== Изменить значение поля записи на явное значение.


NOTE: 



Ключевые слова::
change
update
replace
transform



.Конфигурация
====
    "Replacement Value Strategy" = "Literal Value"

    A single additional property is added to the Processor. The name of the property should indicate a RecordPath identifying the field to place the result in.
    The value of the property is the explicit value to set the field to. For example, we can set any field with a name of `txId`, regardless of its level in the data's hierarchy,     to `1111-1111` by adding a property with a name of `//txId` and a value of `1111-1111`
====


=== Копировать значение одного поля записи в другое поле записи.


NOTE: 



Ключевые слова::
change
update
copy
recordpath
hierarchy
transform



.Конфигурация
====
    "Replacement Value Strategy" = "Record Path Value"

    A single additional property is added to the Processor. The name of the property should indicate a RecordPath identifying the field to update.
    The value of the property should be a RecordPath identifying the field to copy the value from.
    For example, we can copy the value of `/identifiers/all/imei` to the `identifier` field at the root level, by adding a property named     `/identifier` with a value of `/identifiers/all/imei`.
====


=== Обогатить данные, введя значение атрибута в каждую запись.


NOTE: 



Ключевые слова::
enrich
attribute
change
update
replace
insert
transform



.Конфигурация
====
"Replacement Value Strategy" = "Literal Value"

A single additional property is added to the Processor. The name of the property should indicate a RecordPath identifying the field to place the result in.
The value of the property is an Expression Language expression that references the attribute of interest. We can, for example, insert a new field name `filename` into each record by adding a property named `/filename` with a value of `${filename}`
====


=== Изменить формат значения поля записи.


NOTE: Используйте процессор RenameRecordField для изменения имени поля.



Ключевые слова::
change
update
replace
insert
transform
format
date/time
timezone
expression language



.Конфигурация
====
"Replacement Value Strategy" = "Literal Value"

A single additional property is added to the Processor. The name of the property should indicate a RecordPath identifying the field to update.
The value is an Expression Language expression that references the `field.value` variable. For example, to change the date/time format of a field named `txDate` from `year-month-day` format to `month/day/year` format, we add a property named `/txDate` with a value of `${field.value:toDate('yyyy-MM-dd'):format('MM/dd/yyyy')}`. We could also change the timezone of a timestamp field (and insert the timezone for clarity) by using a value of `${field.value:toDate('yyyy-MM-dd HH:mm:ss', 'UTC-0400'):format('yyyy-MM-dd HH:mm:ss Z', 'UTC')}`.
====






=== Смотрите также


* xref:Processors/ConvertRecord.adoc[ConvertRecord]


